import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/components/AppProvider";

export const metadata: Metadata = {
  title: "Not so crazy",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logog.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        suppressHydrationWarning={true}
        className="bg-[#ffffff] dark:bg-[#111111]"
      >
          <AppProvider>
            {children}
          </AppProvider>
      </body>
    </html>
  );
}
