import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import AppProvider from "@/components/AppProvider";

export const metadata: Metadata = {
  title: "Not so crazy",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logog.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        suppressHydrationWarning={true}
        className="bg-[#eaedf2] dark:bg-[#1F1F21]"
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
